import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-200 dark:bg-gray-800 text-gray-900 dark:text-white">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-gray-200 dark:bg-gray-800 text-gray-900 dark:text-white`}>
        {children}
      </body>
    </html>
  );
}
